#simulation config
batch_size: 128
image_size: 28
workers: 1
novel_class_examples: 20
samples: 5000
proportion_switch: 0.1
proportion_image_corrupt: 0.1

#Comet dashboard
comet_workspace: bw4sz

#Projection embedding depth
embedding_size: 16

#Training
gpus: 1
fast_dev_run: False
accelerator:
classifier_epochs: 30
autoencoder_epochs: 25
lr: 0.001

classification_loss_scalar: 1
autoencoder_loss_scalar: 0

#Outlier detection
outlier_threshold: 0.98
distance_threshold: 10
