name: DeepTreeAttention Pytest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: "CI setup"

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
        os:
          - "ubuntu-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Setup uv"
        uses: "astral-sh/setup-uv@v6"
        with:
          enable-cache: true

      - name: "Install dependencies"
        run: "uv sync --extra dev"

      - name: "Run tests"
        run: "uv run pytest -v"
